### ISSUE TITLE
chunking

### ISSUE THREAD

**Issue by marek-j** [Schnouki/git-annex-remote-hubic#2]
Hi,

do I understand correctly, that changing the chunking parameter is only possible when creating the hubic special remote?

Cheers,
Marek

**Comment by Schnouki** [comment]
Hi Marek,

You can actually change the chunk parameters at any time using something like this:

    git annex enableremote my-hubic-remote hubic_chunk_size=10485760

After running this, new uploads will use the new chunk size, and of course you'll still be able to access files uploaded with the old size or with no chunking at all.

However, if you really rely on chunking, there's now a much better [native chunking mechanism in git-annex](http://git-annex.branchable.com/chunking/). So you should use that one instead of the one in the hubiC remote.

Cheers,
Thomas
